name: Publish worker

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            GRAB_SECRET
            TIMESTAMP_KEY
            SIGNATURE_KEY
        env:
          GRAB_SECRET: ${{ secrets.GRAB_SECRET }}
          TIMESTAMP_KEY: ${{ secrets.TIMESTAMP_KEY }}
          SIGNATURE_KEY: ${{ secrets.SIGNATURE_KEY }}